//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> C_id { get; set; }
    
        public virtual Catagory Catagory { get; set; }
    }
}
